# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,dev/setup_build_boost]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install conan
        uses:  BSFishy/pip-action@v1
        with:
          packages: |
            conan

      - name: Download libraries from Conan
        run: |
          mkdir ${{ runner.workspace }}/build/qc/Debug
          conan install ${{ github.workspace }}/conanfile.txt --install-folder ${{ runner.workspace }}/build/qc/

      - name : Get the latest CMake version
        uses: lukka/get-cmake@latest

      - name: Run CMakeLists build for MSVC compiler
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Debug
          buildDirectory: '${{ runner.workspace }}/build/qc'
          buildWithCMake: false
      - name: Run cmake build for the bin-expresions target
        run: |
          cd ${{ runner.workspace }}/build/qc
          cmake --build .

      - name: Launch simple logic example 1
        run: |
          cd ${{ runner.workspace }}/build//qc//sequential_logic_evaluator//Debug
          .\SecondFourthTaskSequentialLogic.exe ${{ github.workspace }}\sequential_logic_evaluator\examples\simple_gates_1.txt

      - name: Launch simple logic example 2
        run: |
          cd ${{ runner.workspace }}/build//qc//sequential_logic_evaluator//Debug
          .\SecondFourthTaskSequentialLogic.exe ${{ github.workspace }}\sequential_logic_evaluator\examples\simple_gates_2.txt

      - name: Launch simple logic example 3
        run: |
          cd ${{ runner.workspace }}/build//qc//sequential_logic_evaluator//Debug
          .\SecondFourthTaskSequentialLogic.exe ${{ github.workspace }}\sequential_logic_evaluator\examples\simple_gates_3.txt

      - name: Launch logic evaluate with broken gate simulation
        run: |
          cd ${{ runner.workspace }}/build//qc//sequential_logic_evaluator//Debug
          .\SecondFourthTaskSequentialLogic.exe ${{ github.workspace }}\sequential_logic_evaluator\examples\gates_with_broken_gate.txt